"""Optimized-Python generation and caching (spec 15.2, 15.3, 15.6)."""

from __future__ import annotations

import ast
import json
from dataclasses import dataclass
from pathlib import Path

from ...cache import CacheKey, CacheStore
from ...opt.manager import OptimizationResult

__all__ = ["GeneratedModule", "emit", "source_map"]

_HEADER = "# generated by ppy; do not edit. source: {source}\n"


@dataclass(slots=True)
class GeneratedModule:
    name: str
    source_path: Path
    code: str
    artifact: Path
    key: str
    line_map: dict[int, int]
    fused_symbols: tuple[str, ...] = ()

    @property
    def needs_fused_binder(self) -> bool:
        return bool(self.fused_symbols)

    def compile(
        self,
        native_names: frozenset[str] = frozenset(),
        exported_names: frozenset[str] = frozenset(),
        region_names: frozenset[str] = frozenset(),
    ) -> object:
        """Compile with the original `.ppy` filename so tracebacks map back."""
        tree = ast.parse(self.code, filename=str(self.source_path))
        _restore_lines(tree, self.line_map)
        bindings = [
            (BINDER_NAME, native_names),
            (EXPORTED_BINDER, exported_names),
            (REGION_BINDER, region_names),
        ]
        if any(names for _binder, names in bindings):
            _insert_definition_bindings(tree, bindings)
        return compile(tree, str(self.source_path), "exec", dont_inherit=True)


def source_map(tree: ast.Module, generated: str) -> dict[int, int]:
    """Map each generated line back to the original `.ppy` line it came from."""
    mapping: dict[int, int] = {}
    generated_tree = ast.parse(generated)
    original_nodes = [n for n in ast.walk(tree) if hasattr(n, "lineno")]
    generated_nodes = [n for n in ast.walk(generated_tree) if hasattr(n, "lineno")]
    for original, emitted in zip(_ordered(original_nodes), _ordered(generated_nodes)):
        mapping.setdefault(emitted.lineno, original.lineno)
    return mapping


def _ordered(nodes: list[ast.AST]) -> list[ast.AST]:
    return sorted(nodes, key=lambda n: (n.lineno, n.col_offset, type(n).__name__))


def _restore_lines(tree: ast.Module, line_map: dict[int, int]) -> None:
    for node in ast.walk(tree):
        if not hasattr(node, "lineno"):
            continue
        original = line_map.get(node.lineno)
        if original is None:
            continue
        node.lineno = original
        if getattr(node, "end_lineno", None) is not None:
            node.end_lineno = max(original, line_map.get(node.end_lineno, original))


def emit(
    name: str,
    source_path: Path,
    result: OptimizationResult,
    store: CacheStore,
    key: CacheKey,
    *,
    dependencies: tuple[str, ...] = (),
) -> GeneratedModule:
    """Unparse the optimized tree and publish it to the cache."""
    body = ast.unparse(result.tree)
    code = _HEADER.format(source=source_path) + body + "\n"
    line_map = source_map(result.tree, body)
    offset = code[: code.index(body)].count("\n")
    line_map = {line + offset: original for line, original in line_map.items()}

    artifact = store.put(
        key,
        code,
        kind="python",
        source=str(source_path),
        dependencies=dependencies,
        suffix=".py",
    )
    store.put(
        f"{key.hex()}.map",
        json.dumps(
            {
                "source": str(source_path),
                "lines": line_map,
                "fused": list(result.fused_symbols),
            },
            indent=1,
        ),
        kind="metadata",
        source=str(source_path),
        suffix=".json",
    )
    return GeneratedModule(
        name=name,
        source_path=source_path,
        code=code,
        artifact=artifact,
        key=key.hex(),
        line_map=line_map,
        fused_symbols=result.fused_symbols,
    )


def _insert_definition_bindings(
    tree: ast.Module, bindings: list[tuple[str, frozenset[str]]]
) -> None:
    """Bind an entry point immediately after its `def`, so every later
    reference -- a top-level `main()`, or a method looked up on its class --
    uses it."""
    tree.body = _bind_in(tree.body, bindings, prefix="")


def _bind_in(
    body: list[ast.stmt], bindings: list[tuple[str, frozenset[str]]], prefix: str
) -> list[ast.stmt]:
    rebuilt: list[ast.stmt] = []
    for statement in body:
        if isinstance(statement, ast.ClassDef):
            statement.body = _bind_in(statement.body, bindings, f"{prefix}{statement.name}.")
            rebuilt.append(statement)
            continue
        rebuilt.append(statement)
        if not isinstance(statement, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        key = f"{prefix}{statement.name}"
        for binder, names in bindings:
            if key not in names:
                continue
            binding = ast.Assign(
                targets=[ast.Name(id=statement.name, ctx=ast.Store())],
                value=ast.Call(
                    func=ast.Name(id=binder, ctx=ast.Load()),
                    args=[
                        ast.Constant(value=key),
                        ast.Name(id=statement.name, ctx=ast.Load()),
                    ],
                    keywords=[],
                ),
            )
            ast.copy_location(binding, statement)
            ast.fix_missing_locations(binding)
            rebuilt.append(binding)
    return rebuilt


#: Names injected into a generated module namespace by the backends.
BINDER_NAME = "__ppy_bind_native__"
EXPORTED_BINDER = "__ppy_bind_exported__"
REGION_BINDER = "__ppy_bind_region__"
