"""Optimized-Python generation and caching (spec 15.2, 15.3, 15.6)."""

from __future__ import annotations

import ast
import json
from pathlib import Path

from ppy_runtime.generated import (
    GeneratedModule,
)

from ...cache import CacheKey, CacheStore
from ...opt.manager import OptimizationResult

__all__ = ["GeneratedModule", "emit", "source_map"]

_HEADER = "# generated by ppy; do not edit. source: {source}\n"


def source_map(tree: ast.Module, generated: str) -> dict[int, int]:
    """Map each generated line back to the original `.ppy` line it came from."""
    mapping: dict[int, int] = {}
    generated_tree = ast.parse(generated)
    original_nodes = [n for n in ast.walk(tree) if hasattr(n, "lineno")]
    generated_nodes = [n for n in ast.walk(generated_tree) if hasattr(n, "lineno")]
    for original, emitted in zip(_ordered(original_nodes), _ordered(generated_nodes), strict=False):
        mapping.setdefault(emitted.lineno, original.lineno)
    return mapping


def _ordered(nodes: list[ast.AST]) -> list[ast.AST]:
    return sorted(nodes, key=lambda n: (n.lineno, n.col_offset, type(n).__name__))


def emit(
    name: str,
    source_path: Path,
    result: OptimizationResult,
    store: CacheStore,
    key: CacheKey,
    *,
    dependencies: tuple[str, ...] = (),
) -> GeneratedModule:
    """Unparse the optimized tree and publish it to the cache."""
    body = ast.unparse(result.tree)
    code = _HEADER.format(source=source_path) + body + "\n"
    line_map = source_map(result.tree, body)
    offset = code[: code.index(body)].count("\n")
    line_map = {line + offset: original for line, original in line_map.items()}

    artifact = store.put(
        key,
        code,
        kind="python",
        source=str(source_path),
        dependencies=dependencies,
        suffix=".py",
    )
    store.put(
        f"{key.hex()}.map",
        json.dumps(
            {
                "source": str(source_path),
                "lines": line_map,
                "fused": list(result.fused_symbols),
            },
            indent=1,
        ),
        kind="metadata",
        source=str(source_path),
        suffix=".json",
    )
    return GeneratedModule(
        name=name,
        source_path=source_path,
        code=code,
        artifact=artifact,
        key=key.hex(),
        line_map=line_map,
        fused_symbols=result.fused_symbols,
    )
