"""Generated CPython-ABI wrappers for native functions (spec 16.4, 16.5).

A compiled PPY function has two entry points. Statically compiled PPY callers
use the native ABI directly. Python callers go through the wrapper generated
here, which parses arguments, applies the guards, invokes the native code, and
boxes the result -- using the version-specific CPython C API, because that is
what makes the boundary cheap enough for the native path to be worth taking.

A guard that fails returns `NotImplemented`, which is the signal to re-run the
original Python implementation.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .lowering import NativeParam, NativeSignature

__all__ = ["WrapperModule", "generate", "C_TYPES"]

#: The C spelling of each ABI atom.
C_TYPES = {"i64": "long long", "double": "double", "i8": "char"}

_HEADER = """/* generated by ppy; do not edit. */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdint.h>

/* A guard that fails hands the call back to the Python implementation. */
#define PPY_GUARD_FAIL() do { PyErr_Clear(); goto ppy_fallback; } while (0)
"""

_FOOTER = """
static PyMethodDef ppy_methods[] = {{
{methods}
    {{NULL, NULL, 0, NULL}}
}};

static struct PyModuleDef ppy_module = {{
    PyModuleDef_HEAD_INIT, "{name}", NULL, -1, ppy_methods, NULL, NULL, NULL, NULL
}};

PyMODINIT_FUNC PyInit_{name}(void) {{
    return PyModule_Create(&ppy_module);
}}
"""


@dataclass(slots=True)
class WrapperModule:
    """The C source for one module's Python-ABI entry points."""

    name: str
    source: str
    entries: dict[str, int] = field(default_factory=dict)

    def bind_name(self, index: int) -> str:
        return f"bind_{index}"

    def call_name(self, index: int) -> str:
        return f"call_{index}"


def generate(name: str, signatures: dict[str, NativeSignature]) -> WrapperModule:
    """Build the wrapper module for a set of native functions."""
    parts = [_HEADER]
    methods: list[str] = []
    entries: dict[str, int] = {}

    for index, (qualname, signature) in enumerate(sorted(signatures.items())):
        entries[qualname] = index
        parts.append(_function(index, signature))
        methods.append(
            f'    {{"bind_{index}", ppy_bind_{index}, METH_VARARGS, NULL}},'
        )
        methods.append(
            f'    {{"call_{index}", (PyCFunction)(void *)ppy_call_{index}, '
            f"METH_FASTCALL, NULL}},"
        )

    parts.append(_FOOTER.format(methods="\n".join(methods), name=name))
    return WrapperModule(name=name, source="\n".join(parts), entries=entries)


def _function(index: int, signature: NativeSignature) -> str:
    atoms = [C_TYPES[atom.removesuffix("*")] + ("*" if atom.endswith("*") else "")
             for atom in signature.params]
    outs = [f"{C_TYPES[atom]} *" for atom in signature.returns]
    pointer = f"ppy_fn_{index}"

    object_params = [p for p in signature.parameters if p.is_object]
    type_slots = "\n".join(
        f"static PyTypeObject *ppy_type_{index}_{position} = NULL;"
        for position, _p in enumerate(object_params)
    )
    # Field names are interned once, so a call is a dict lookup rather than a
    # fresh string on every attribute read.
    name_slots = "\n".join(
        f"static PyObject *ppy_name_{index}_{position}_{offset} = NULL;"
        for position, parameter in enumerate(object_params)
        for offset, _field in enumerate(parameter.fields)
    )

    declarations, body, cleanup, arguments = _parse_arguments(index, signature)
    out_declarations = "\n".join(
        f"    {C_TYPES[atom]} ppy_out{position};" for position, atom in enumerate(signature.returns)
    )
    out_arguments = ", ".join(f"&ppy_out{position}" for position in range(len(signature.returns)))
    call_arguments = ", ".join([*arguments, out_arguments]) if arguments else out_arguments

    builder = _result_builder(index, signature)
    return f"""
/* {signature.qualname}: {signature} */
typedef int (*{pointer})({", ".join([*atoms, *outs])});
static {pointer} ppy_target_{index} = NULL;
static PyObject *ppy_types_{index} = NULL;
{type_slots}
{name_slots}
{builder}

static PyObject *ppy_bind_{index}(PyObject *self, PyObject *args) {{
    unsigned long long address;
    PyObject *types;
    if (!PyArg_ParseTuple(args, "KO", &address, &types)) {{
        return NULL;
    }}
    Py_XINCREF(types);
    Py_XDECREF(ppy_types_{index});
    ppy_types_{index} = types;
    ppy_target_{index} = ({pointer})(uintptr_t)address;
{_type_assignments(index, object_params)}    Py_RETURN_NONE;
}}

static PyObject *ppy_call_{index}(PyObject *self, PyObject *const *args, Py_ssize_t nargs) {{
    if (ppy_target_{index} == NULL || nargs != {len(signature.parameters)}) {{
        Py_RETURN_NOTIMPLEMENTED;
    }}
{declarations}
{body}
{out_declarations}
    int status = ppy_target_{index}({call_arguments});
{cleanup}
    if (status != 0) {{
        Py_RETURN_NOTIMPLEMENTED;
    }}
    return {_box(signature).replace("ppy_build_result(", f"ppy_build_result_{index}(")};

ppy_fallback:
{cleanup}
    Py_RETURN_NOTIMPLEMENTED;
}}
"""


def _type_assignments(index: int, object_params: list[NativeParam]) -> str:
    lines = []
    for position, parameter in enumerate(object_params):
        lines.append(
            f"    ppy_type_{index}_{position} = "
            f"(PyTypeObject *)PyTuple_GetItem(types, {position});"
        )
        for offset, (field, _scalar) in enumerate(parameter.fields):
            slot = f"ppy_name_{index}_{position}_{offset}"
            lines.append(f'    if ({slot} == NULL) {slot} = PyUnicode_InternFromString("{field}");')
            lines.append(f"    if ({slot} == NULL) return NULL;")
    return "\n".join(lines) + ("\n" if lines else "")


def _parse_arguments(
    index: int, signature: NativeSignature
) -> tuple[str, str, str, list[str]]:
    """Emit the declarations, the parsing, the cleanup, and the call arguments.

    Every variable is declared and initialized up front, because a guard that
    fails jumps to the cleanup: a declaration skipped by that jump would leave
    the cleanup reading an indeterminate value.
    """
    declarations: list[str] = []
    lines: list[str] = []
    cleanup: list[str] = []
    arguments: list[str] = []
    object_position = 0

    for position, parameter in enumerate(signature.parameters):
        source = f"args[{position}]"
        if parameter.is_object:
            slot = f"ppy_type_{index}_{object_position}"
            object_position += 1
            lines.append(
                f"    if ({slot} == NULL || Py_TYPE({source}) != {slot}) "
                f"PPY_GUARD_FAIL();"
            )
            for offset, (field, scalar) in enumerate(parameter.fields):
                name = f"a{position}_{field}"
                interned = f"ppy_name_{index}_{object_position - 1}_{offset}"
                declarations.append(f"    {C_TYPES[_abi(scalar)]} {name} = 0;")
                lines.append(f"    {{")
                lines.append(
                    f"        PyObject *member = PyObject_GetAttr({source}, {interned});"
                )
                lines.append("        if (member == NULL) PPY_GUARD_FAIL();")
                lines.extend(_scalar_lines(scalar, "member", name, "        ", release=True))
                lines.append("        Py_DECREF(member);")
                lines.append("    }")
                arguments.append(name)
            continue

        if parameter.is_tuple:
            lines.append(
                f"    if (!PyTuple_CheckExact({source}) || "
                f"PyTuple_GET_SIZE({source}) != {len(parameter.elements)}) PPY_GUARD_FAIL();"
            )
            for offset, scalar in enumerate(parameter.elements):
                name = f"a{position}_{offset}"
                declarations.append(f"    {C_TYPES[_abi(scalar)]} {name} = 0;")
                lines.extend(
                    _scalar_lines(scalar, f"PyTuple_GET_ITEM({source}, {offset})", name, "    ")
                )
                arguments.append(name)
            continue

        if parameter.is_borrowed:
            view = f"view{position}"
            declarations.append(f"    Py_buffer {view};")
            declarations.append(f"    int {view}_held = 0;")
            lines.append(
                f"    if (PyObject_GetBuffer({source}, &{view}, "
                f"PyBUF_WRITABLE | PyBUF_C_CONTIGUOUS | PyBUF_FORMAT) != 0) PPY_GUARD_FAIL();"
            )
            lines.append(f"    {view}_held = 1;")
            lines.append(
                f"    if ({view}.ndim != 1 || {view}.itemsize != {_itemsize(parameter.element)}"
                f" || {view}.format == NULL || !({_format_test(parameter.element, view)}))"
                f" PPY_GUARD_FAIL();"
            )
            cleanup.append(f"    if ({view}_held) PyBuffer_Release(&{view});")
            arguments.append(f"({C_TYPES[_abi(parameter.element)]} *){view}.buf")
            arguments.append(f"(long long){view}.shape[0]")
            continue

        if parameter.is_buffer:
            data = f"data{position}"
            count = f"count{position}"
            element = C_TYPES[_abi(parameter.element)]
            declarations.append(f"    {element} *{data} = NULL;")
            declarations.append(f"    Py_ssize_t {count} = 0;")
            lines.append(f"    if (!PyList_CheckExact({source})) PPY_GUARD_FAIL();")
            lines.append(f"    {count} = PyList_GET_SIZE({source});")
            lines.append(
                f"    {data} = ({element} *)PyMem_Malloc((size_t)({count} ? {count} : 1)"
                f" * sizeof({element}));"
            )
            lines.append(f"    if ({data} == NULL) PPY_GUARD_FAIL();")
            lines.append(f"    for (Py_ssize_t i = 0; i < {count}; i++) {{")
            lines.append(f"        PyObject *item = PyList_GET_ITEM({source}, i);")
            lines.extend(_scalar_lines(parameter.element, "item", f"{data}[i]", "        ",
                                       declare=False))
            lines.append("    }")
            cleanup.append(f"    PyMem_Free({data});")
            arguments.append(data)
            arguments.append(f"(long long){count}")
            continue

        name = f"a{position}"
        declarations.append(f"    {C_TYPES[_abi(parameter.kind)]} {name} = 0;")
        lines.extend(_scalar_lines(parameter.kind, source, name, "    "))
        arguments.append(name)

    return "\n".join(declarations), "\n".join(lines), "\n".join(cleanup), arguments


def _scalar_lines(
    scalar: str,
    source: str,
    target: str,
    indent: str,
    *,
    declare: bool = True,
    release: bool = False,
) -> list[str]:
    """Parse one Python object into a machine scalar, or fail the guard."""
    undo = f"{indent}    Py_DECREF({source});\n" if release else ""
    if scalar == "float":
        return [
            f"{indent}if (PyFloat_CheckExact({source})) {{",
            f"{indent}    {target} = PyFloat_AS_DOUBLE({source});",
            f"{indent}}} else if (PyLong_CheckExact({source})) {{",
            f"{indent}    {target} = PyLong_AsDouble({source});",
            f"{indent}    if ({target} == -1.0 && PyErr_Occurred()) {{",
            f"{undo}{indent}        PPY_GUARD_FAIL();",
            f"{indent}    }}",
            f"{indent}}} else {{",
            f"{undo}{indent}    PPY_GUARD_FAIL();",
            f"{indent}}}",
        ]
    if scalar == "bool":
        return [
            f"{indent}if (!PyBool_Check({source})) {{",
            f"{undo}{indent}    PPY_GUARD_FAIL();",
            f"{indent}}}",
            f"{indent}{target} = ({source} == Py_True) ? 1 : 0;",
        ]
    return [
        f"{indent}if (!PyLong_CheckExact({source})) {{",
        f"{undo}{indent}    PPY_GUARD_FAIL();",
        f"{indent}}}",
        f"{indent}{target} = PyLong_AsLongLong({source});",
        f"{indent}if ({target} == -1 && PyErr_Occurred()) {{",
        f"{undo}{indent}    PPY_GUARD_FAIL();",
        f"{indent}}}",
    ]


def _box(signature: NativeSignature) -> str:
    """Build the Python object the wrapper returns."""
    if len(signature.returns) == 1:
        return _box_one(signature.returns[0], "ppy_out0")
    return "ppy_build_result(" + ", ".join(
        f"ppy_out{position}" for position in range(len(signature.returns))
    ) + ")"


def _result_builder(index: int, signature: NativeSignature) -> str:
    """A tuple result is built element by element, so no format string is
    needed and a failed allocation cannot leak the elements already boxed."""
    if len(signature.returns) == 1:
        return ""
    parameters = ", ".join(
        f"{C_TYPES[atom]} v{position}" for position, atom in enumerate(signature.returns)
    )
    sets = "\n".join(
        f"    PyObject *b{position} = {_box_one(atom, f'v{position}')};\n"
        f"    if (b{position} == NULL) {{ Py_DECREF(result); return NULL; }}\n"
        f"    PyTuple_SET_ITEM(result, {position}, b{position});"
        for position, atom in enumerate(signature.returns)
    )
    return f"""
static PyObject *ppy_build_result_{index}({parameters}) {{
    PyObject *result = PyTuple_New({len(signature.returns)});
    if (result == NULL) return NULL;
{sets}
    return result;
}}
"""


def _box_one(atom: str, name: str) -> str:
    if atom == "double":
        return f"PyFloat_FromDouble({name})"
    if atom == "i8":
        return f"PyBool_FromLong({name})"
    return f"PyLong_FromLongLong({name})"


def _abi(scalar: str) -> str:
    return {"int": "i64", "float": "double", "bool": "i8"}[scalar]


def _itemsize(element: str) -> int:
    return 8


def _format_test(element: str, view: str) -> str:
    codes = ("d",) if element == "float" else ("q", "l")
    return " || ".join(f"{view}.format[0] == '{code}'" for code in codes)
