"""Generated CPython-ABI wrappers for native functions (spec 16.4, 16.5).

A compiled PPY function has two entry points. Statically compiled PPY callers
use the native ABI directly. Python callers go through the wrapper generated
here, which parses arguments, applies the guards, invokes the native code, and
boxes the result -- using the version-specific CPython C API, because that is
what makes the boundary cheap enough for the native path to be worth taking.

A guard that fails returns `NotImplemented`, which is the signal to re-run the
original Python implementation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from ppy_runtime.abi import CrossingClass
from ppy_runtime.collection_boundary import Spec, field_spec
from ppy_runtime.collection_boundary import parse as parse_spec

from .lowering import NativeParam, NativeSignature

__all__ = ["C_TYPES", "WrapperModule", "crosses_in_c", "generate"]

#: The C spelling of each ABI atom.
C_TYPES = {"i64": "long long", "double": "double", "i8": "char"}

_HEADER = """/* generated by ppy; do not edit. */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdint.h>
#include <stdlib.h>
#if defined(__unix__) || defined(__APPLE__)
#include <dlfcn.h>
#endif

/* A guard that fails hands the call back to the Python implementation. */
#define PPY_GUARD_FAIL() do { PyErr_Clear(); goto ppy_fallback; } while (0)

/* A sanitizer's check failed: the status names the kind, and the error is the
 * runtime's SanitizerFailure, never a hand-off to Python. */
static const char *ppy_sanitizer_names[] = {"bounds", "overflow", "pointer", "alignment"};
static PyObject *ppy_sanitizer_failed(int status, const char *qualname) {
    int kind = status - 2;
    if (kind < 0 || kind > 3) kind = 3;
    PyObject *module = PyImport_ImportModule("ppy_runtime.binding");
    PyObject *failure = module ? PyObject_GetAttrString(module, "SanitizerFailure") : NULL;
    if (failure == NULL) {
        PyErr_Clear();
    }
    PyErr_Format(failure ? failure : PyExc_RuntimeError,
                 "sanitizer: a %s check failed in `%s`", ppy_sanitizer_names[kind], qualname);
    Py_XDECREF(failure);
    Py_XDECREF(module);
    return NULL;
}

/* A string result: the UTF-8 copy the native code made, read and freed. */
static PyObject *ppy_text_result(char *data, long long length) {
    PyObject *made = PyUnicode_DecodeUTF8(data, (Py_ssize_t)length, NULL);
    free(data);
    return made;
}

/* The Python implementation, invoked from C when a guard refuses the call.
 * Holding the fallback here removes a Python dispatch frame from every
 * refusal -- and from every acceptance, because the caller no longer needs a
 * Python wrapper watching for NotImplemented. */
/* A call that ended on an exception nothing native caught: Python runs it
 * again and raises it, and what the native call made, the exception with
 * it, is garbage the collections runtime frees at once. The runtime is the
 * copy in the library the native function is in. */
static void ppy_raised(void *native) {
#if defined(__unix__) || defined(__APPLE__)
    void (*sweep)(void) = NULL;
    Dl_info found;
    if (dladdr(native, &found) && found.dli_fname != NULL) {
        void *library = dlopen(found.dli_fname, RTLD_LAZY | RTLD_NOLOAD);
        if (library != NULL) {
            *(void **)(&sweep) = dlsym(library, "ppy_coll_sweep");
            dlclose(library);
        }
    }
    if (sweep == NULL) {
        *(void **)(&sweep) = dlsym(RTLD_DEFAULT, "ppy_coll_sweep");
    }
    if (sweep != NULL) {
        sweep();
    }
#else
    (void)native;
#endif
}

static PyObject *ppy_handoff(PyObject *fallback, PyObject *const *args, Py_ssize_t nargs) {
    if (fallback == NULL) {
        Py_RETURN_NOTIMPLEMENTED;
    }
    return PyObject_Vectorcall(fallback, args, nargs, NULL);
}

/* The fallback, called as the caller spelled the call. */
static PyObject *ppy_handoff_as(
    PyObject *fallback, PyObject *const *args, Py_ssize_t nargs, PyObject *kwnames
) {
    if (fallback == NULL) {
        Py_RETURN_NOTIMPLEMENTED;
    }
    return PyObject_Vectorcall(fallback, args, nargs, kwnames);
}

/* A call spelled with keywords, or with defaults left out, bound here as
 * Python binds it: by the Python function's parameter names, and with its
 * defaults, read at each call as `__defaults__` and `__kwdefaults__` hold
 * them. Anything this does not bind plainly (a name it does not know, one
 * given twice, a positional-only one by name, too many arguments, a missing
 * one with no default) is the Python function's to bind, which raises
 * CPython's own TypeError for it. */
typedef struct {
    PyObject *function; /* the Python function, or NULL: nothing binds here */
    PyObject *names;    /* its parameters' names, in the native entry's order */
    Py_ssize_t posonly;    /* the leading ones only passed by position */
    Py_ssize_t positional; /* the ones that can be passed by position */
} ppy_binder;

static Py_ssize_t ppy_code_count(PyObject *code, const char *name) {
    PyObject *value = PyObject_GetAttrString(code, name);
    Py_ssize_t found = value != NULL && PyLong_Check(value) ? PyLong_AsSsize_t(value) : -1;
    Py_XDECREF(value);
    return found;
}

/* Bind by `function`, whose parameters must be the entry's `count` in order:
 * no `*args` and no `**kwargs`. Any other function binds nothing here. */
static void ppy_binder_set(ppy_binder *binder, PyObject *function, Py_ssize_t count) {
    PyObject *code;
    PyObject *varnames = NULL;
    Py_ssize_t flags, positional, posonly, kwonly;
    Py_CLEAR(binder->function);
    Py_CLEAR(binder->names);
    if (function == NULL || !PyFunction_Check(function)) {
        return;
    }
    code = PyFunction_GetCode(function);
    flags = ppy_code_count(code, "co_flags");
    positional = ppy_code_count(code, "co_argcount");
    posonly = ppy_code_count(code, "co_posonlyargcount");
    kwonly = ppy_code_count(code, "co_kwonlyargcount");
    varnames = PyObject_GetAttrString(code, "co_varnames");
    /* 0x04 is CO_VARARGS and 0x08 CO_VARKEYWORDS. */
    if (flags < 0 || positional < 0 || posonly < 0 || kwonly < 0 || (flags & 0x0C) != 0
        || positional + kwonly != count || varnames == NULL || !PyTuple_Check(varnames)
        || PyTuple_GET_SIZE(varnames) < count) {
        Py_XDECREF(varnames);
        PyErr_Clear();
        return;
    }
    binder->names = PyTuple_GetSlice(varnames, 0, count);
    Py_DECREF(varnames);
    if (binder->names == NULL) {
        PyErr_Clear();
        return;
    }
    Py_INCREF(function);
    binder->function = function;
    binder->posonly = posonly;
    binder->positional = positional;
}

/* 1 where the call bound into `bound`, a borrowed reference per parameter;
 * 0 where Python must bind it. */
static int ppy_bind_call(
    const ppy_binder *binder, PyObject *const *args, Py_ssize_t nargs, PyObject *kwnames,
    PyObject **bound, Py_ssize_t count
) {
    Py_ssize_t keywords = kwnames != NULL ? PyTuple_GET_SIZE(kwnames) : 0;
    PyObject *defaults;
    Py_ssize_t first;
    if (binder->function == NULL || nargs > binder->positional) {
        return 0;
    }
    for (Py_ssize_t i = 0; i < count; i++) {
        bound[i] = i < nargs ? args[i] : NULL;
    }
    for (Py_ssize_t k = 0; k < keywords; k++) {
        PyObject *key = PyTuple_GET_ITEM(kwnames, k);
        Py_ssize_t at = -1;
        for (Py_ssize_t i = binder->posonly; i < count && at < 0; i++) {
            if (PyTuple_GET_ITEM(binder->names, i) == key) {
                at = i;
            }
        }
        for (Py_ssize_t i = binder->posonly; i < count && at < 0; i++) {
            /* A name the caller made rather than spelled is equal, not the same. */
            if (PyUnicode_Compare(PyTuple_GET_ITEM(binder->names, i), key) == 0) {
                at = i;
            }
        }
        if (PyErr_Occurred()) {
            PyErr_Clear();
            return 0;
        }
        if (at < 0 || bound[at] != NULL) {
            return 0;
        }
        bound[at] = args[nargs + k];
    }
    defaults = PyFunction_GetDefaults(binder->function);
    first = binder->positional - (defaults != NULL ? PyTuple_GET_SIZE(defaults) : 0);
    for (Py_ssize_t i = nargs; i < count; i++) {
        if (bound[i] != NULL) {
            continue;
        }
        if (i < binder->positional) {
            if (defaults == NULL || i < first) {
                return 0;
            }
            bound[i] = PyTuple_GET_ITEM(defaults, i - first);
        } else {
            PyObject *named = PyFunction_GetKwDefaults(binder->function);
            PyObject *value = named != NULL && PyDict_Check(named)
                ? PyDict_GetItemWithError(named, PyTuple_GET_ITEM(binder->names, i))
                : NULL;
            if (value == NULL) {
                PyErr_Clear();
                return 0;
            }
            bound[i] = value;
        }
    }
    return 1;
}

/* The entry that stands in for a Python function answers to its name, its
 * module, and its docstring, so `help`, `doctest`, and `__name__` see the
 * function the program wrote rather than the wrapper module's table entry. */
static PyObject *ppy_named(PyCFunction call, PyObject *fallback) {
    PyObject *name = PyObject_GetAttrString(fallback, "__name__");
    PyObject *doc = PyObject_GetAttrString(fallback, "__doc__");
    PyObject *module = PyObject_GetAttrString(fallback, "__module__");
    PyObject *entry = NULL;
    PyMethodDef *def = NULL;
    const char *text;
    if (name == NULL || doc == NULL || module == NULL || !PyUnicode_Check(name)) {
        goto done;
    }
    def = (PyMethodDef *)PyMem_RawCalloc(1, sizeof(PyMethodDef));
    if (def == NULL) {
        PyErr_NoMemory();
        goto done;
    }
    text = PyUnicode_AsUTF8(name);
    def->ml_name = text != NULL ? strdup(text) : NULL;
    if (def->ml_name == NULL) {
        goto done;
    }
    if (PyUnicode_Check(doc)) {
        text = PyUnicode_AsUTF8(doc);
        def->ml_doc = text != NULL ? strdup(text) : NULL;
    }
    def->ml_meth = call;
    def->ml_flags = METH_FASTCALL | METH_KEYWORDS;
    entry = PyCFunction_NewEx(def, NULL, module);
done:
    Py_XDECREF(name);
    Py_XDECREF(doc);
    Py_XDECREF(module);
    if (entry == NULL) {
        /* An entry that could not be named is still correct: the caller falls
         * back to the table's own, which it finds by name. */
        PyErr_Clear();
        Py_RETURN_NONE;
    }
    return entry;
}

#define PPY_MAX_SPECS 8
#define PPY_MAX_PINS 8

/* One argument fact a specialization was compiled for. Checking these here
 * rather than in Python is what lets a specialized function keep the cheap
 * boundary (spec 16.9). */
typedef struct {
    int kind; /* 1 = integer value, 2 = float value, 3 = length */
    int index;
    long long ivalue;
    double dvalue;
} ppy_pin;

typedef struct {
    int count;
    ppy_pin pins[PPY_MAX_PINS];
    void *target;
} ppy_spec;

static int ppy_spec_matches(const ppy_spec *spec, PyObject *const *args, Py_ssize_t nargs) {
    for (int i = 0; i < spec->count; i++) {
        const ppy_pin *pin = &spec->pins[i];
        if (pin->index >= nargs) {
            return 0;
        }
        PyObject *arg = args[pin->index];
        if (pin->kind == 1) {
            int overflow = 0;
            long long value;
            if (!PyLong_CheckExact(arg)) {
                return 0;
            }
            value = PyLong_AsLongLongAndOverflow(arg, &overflow);
            if (overflow != 0 || value != pin->ivalue) {
                return 0;
            }
        } else if (pin->kind == 2) {
            if (!PyFloat_CheckExact(arg) || PyFloat_AS_DOUBLE(arg) != pin->dvalue) {
                return 0;
            }
        } else {
            Py_ssize_t length = PyObject_Length(arg);
            if (length < 0) {
                PyErr_Clear();
                return 0;
            }
            if ((long long)length != pin->ivalue) {
                return 0;
            }
        }
    }
    return 1;
}

/* Records one specialization: its pinned facts and the code compiled for them. */
static int ppy_add_spec(ppy_spec *specs, int *count, PyObject *args) {
    unsigned long long address;
    PyObject *pins;
    Py_ssize_t total;
    ppy_spec *slot;

    if (!PyArg_ParseTuple(args, "KO", &address, &pins)) {
        return -1;
    }
    if (!PyTuple_CheckExact(pins)) {
        PyErr_SetString(PyExc_TypeError, "pins must be a tuple");
        return -1;
    }
    total = PyTuple_GET_SIZE(pins);
    if (*count >= PPY_MAX_SPECS || total > PPY_MAX_PINS) {
        return 0;
    }
    slot = &specs[*count];
    slot->count = (int)total;
    slot->target = (void *)(uintptr_t)address;
    for (Py_ssize_t i = 0; i < total; i++) {
        PyObject *pin = PyTuple_GET_ITEM(pins, i);
        int kind, index;
        PyObject *value;
        if (!PyArg_ParseTuple(pin, "iiO", &kind, &index, &value)) {
            return -1;
        }
        slot->pins[i].kind = kind;
        slot->pins[i].index = index;
        slot->pins[i].ivalue = 0;
        slot->pins[i].dvalue = 0.0;
        if (kind == 2) {
            slot->pins[i].dvalue = PyFloat_AsDouble(value);
            if (slot->pins[i].dvalue == -1.0 && PyErr_Occurred()) {
                return -1;
            }
        } else {
            slot->pins[i].ivalue = PyLong_AsLongLong(value);
            if (slot->pins[i].ivalue == -1 && PyErr_Occurred()) {
                return -1;
            }
        }
    }
    *count += 1;
    return 1;
}
"""

#: The containers' crossing (`crossing.c`), added to a module whose
#: functions take or return a `list`, a `dict`, or a `set`, and the held
#: output of functions with effects (`wrapper_effects.c`).
_CROSSING = Path(__file__).with_name("crossing.c")
_EFFECTS = Path(__file__).with_name("wrapper_effects.c")


def _support(signatures, *, managed: bool = True) -> list[str]:  # type: ignore[no-untyped-def]
    """The C the wrappers of these signatures share."""
    found = list(signatures)
    parts = []
    if any(s.crosses_collections for s in found):
        parts.append(_CROSSING.read_text(encoding="utf-8"))
    if managed and any(s.effects for s in found):
        parts.append(_EFFECTS.read_text(encoding="utf-8"))
    if managed and any(s.draws for s in found):
        parts.append(_DRAWS)
    return parts


#: A function that draws from `random` draws in `random._inst`'s own state,
#: which the binder hands over (`ppy_random`): the wrapper saves it before the
#: call and puts it back where the call falls back, so the Python body draws
#: what native code drew, and forgets `gauss_next` where native code seeded,
#: as `random.seed` does. `binding._SharedGenerator` does the same in Python.
_DRAWS = r"""
#include <string.h>
#define PPY_DRAW_BYTES (4 + 624 * 4)
static unsigned char *ppy_draw_state = NULL;
static int64_t (*ppy_draw_reseeded)(void) = NULL;
static PyObject *ppy_draw_inst = NULL;

/* `ppy_random(state address, reseeded address, random._inst)`. */
static PyObject *ppy_random(PyObject *self, PyObject *args) {
    unsigned long long state, reseeded;
    PyObject *inst;
    (void)self;
    if (!PyArg_ParseTuple(args, "KKO", &state, &reseeded, &inst)) {
        return NULL;
    }
    if (state == 0 || reseeded == 0) {
        Py_RETURN_FALSE;
    }
    Py_INCREF(inst);
    Py_XDECREF(ppy_draw_inst);
    ppy_draw_inst = inst;
    *(void **)(&ppy_draw_reseeded) = (void *)(uintptr_t)reseeded;
    ppy_draw_state = (unsigned char *)(uintptr_t)state;
    Py_RETURN_TRUE;
}

/* The state as the call found it, before Python runs the call again. */
static void ppy_draw_restore(const unsigned char *saved) {
    if (ppy_draw_state == NULL) {
        return;
    }
    memcpy(ppy_draw_state, saved, PPY_DRAW_BYTES);
    ppy_draw_reseeded();
}

/* After a call that answered: `gauss_next` forgotten where it seeded. */
static void ppy_draw_settle(void) {
    if (ppy_draw_state == NULL || !ppy_draw_reseeded()) {
        return;
    }
    if (PyObject_SetAttrString(ppy_draw_inst, "gauss_next", Py_None) < 0) {
        PyErr_Clear();
    }
}
"""


_FOOTER = """
static PyMethodDef ppy_methods[] = {{
{methods}
    {{NULL, NULL, 0, NULL}}
}};

static struct PyModuleDef ppy_module = {{
    PyModuleDef_HEAD_INIT, "{name}", NULL, -1, ppy_methods, NULL, NULL, NULL, NULL
}};

PyMODINIT_FUNC PyInit_{name}(void) {{
    return PyModule_Create(&ppy_module);
}}
"""


@dataclass(slots=True)
class WrapperModule:
    """The C source for one module's Python-ABI entry points."""

    name: str
    source: str
    entries: dict[str, int] = field(default_factory=dict)

    def bind_name(self, index: int) -> str:
        return f"bind_{index}"

    def call_name(self, qualname: str) -> str:
        return qualname


def generate(name: str, signatures: dict[str, NativeSignature]) -> WrapperModule:
    """Build the wrapper module for a set of native functions."""
    parts = [_HEADER]
    methods: list[str] = []
    entries: dict[str, int] = {}

    # A collection this wrapper cannot copy crosses through
    # `ppy_runtime.collection_boundary`, which the Python-level binding
    # drives, and so does a global the binding reads; there is no C wrapper
    # for either.
    signatures = {q: s for q, s in signatures.items() if wrapped_in_c(s)}
    parts.extend(_support(signatures.values()))
    if any(s.crosses_collections for s in signatures.values()):
        methods.append('    {"ppy_runtime", ppy_runtime, METH_VARARGS, NULL},')
        methods.append('    {"ppy_world", ppy_world, METH_VARARGS, NULL},')
        methods.append('    {"ppy_world_stats", ppy_world_stats, METH_NOARGS, NULL},')
    if any(s.effects for s in signatures.values()):
        methods.append('    {"ppy_effects", ppy_effects, METH_VARARGS, NULL},')
    if any(s.draws for s in signatures.values()):
        methods.append('    {"ppy_random", ppy_random, METH_VARARGS, NULL},')
    for index, (qualname, signature) in enumerate(sorted(signatures.items())):
        entries[qualname] = index
        parts.append(_function(index, signature))
        methods.append(f'    {{"bind_{index}", ppy_bind_{index}, METH_VARARGS, NULL}},')
        methods.append(f'    {{"specialize_{index}", ppy_specialize_{index}, METH_VARARGS, NULL}},')
        methods.append(f'    {{"keyed_{index}", ppy_keyed_set_{index}, METH_VARARGS, NULL}},')
        # The entry point stands in the module's namespace in the function's
        # place, so it bears the function's qualified name (`mod.f`,
        # `mod.Class.method`) rather than an index.
        methods.append(
            f'    {{"{qualname}", (PyCFunction)(void *)ppy_call_{index}, '
            "METH_FASTCALL | METH_KEYWORDS, NULL},"
        )

    parts.append(_FOOTER.format(methods="\n".join(methods), name=name))
    return WrapperModule(name=name, source="\n".join(parts), entries=entries)


#: The kinds `crossing.c` copies, by `Spec.kind`.
_CROSSING_KINDS = {
    "int": "PX_INT",
    "float": "PX_FLOAT",
    "bool": "PX_BOOL",
    "str": "PX_STR",
    "tuple": "PX_TUPLE",
    "list": "PX_LIST",
    "dict": "PX_DICT",
    "set": "PX_SET",
    "object": "PX_OBJECT",
    "record": "PX_RECORD",
}

_PARTS = {"int": "i", "float": "f", "bool": "b"}


@dataclass(slots=True)
class _Crossing:
    """What a signature's wrapper copies: each crossed type by its parameter's
    position (`r` the result), and the classes its objects are instances of,
    each with its fields' types."""

    specs: dict[str, Spec]
    classes: list[CrossingClass]
    fields: dict[str, list[tuple[str, int, Spec]]]


def _copied(spec: Spec | None, classes: dict[str, CrossingClass]) -> bool:
    """Whether `crossing.c` copies this type: numbers, strings, tuples of
    numbers, Python's own containers, objects, and value classes."""
    if spec is None or spec.kind not in _CROSSING_KINDS:
        return False
    if spec.kind in {"tuple", "record"} and len(spec.parts) > 32:
        return False
    if spec.kind in {"object", "record"} and spec.record not in classes:
        return False
    return all(_copied(inner, classes) for inner in (spec.key, spec.value) if inner is not None)


def _crossing(signature: NativeSignature) -> _Crossing | None:
    """What the wrapper copies, or None where a type is not one `crossing.c`
    copies: a `ppy` collection, a class with a field native code cannot
    hold."""
    described = {c.qualname: c for c in signature.classes}
    fields: dict[str, list[tuple[str, int, Spec]]] = {}
    for c in signature.classes:
        if c.kind == "record":
            if any(kind not in _PARTS for _name, _offset, kind in c.fields):
                return None
            continue
        parsed = []
        for name, offset, spelled in c.fields:
            spec = field_spec(spelled, described)
            if not _copied(spec, described):
                return None
            assert spec is not None
            parsed.append((name, offset, spec))
        fields[c.qualname] = parsed
    specs: dict[str, Spec] = {}
    for position, parameter in enumerate(signature.parameters):
        if not parameter.is_handle:
            continue
        spec = parse_spec(parameter.element + ("?" if parameter.nullable else ""), described)
        if not _copied(spec, described):
            return None
        assert spec is not None
        specs[str(position)] = spec
    if signature.returned and not signature.returns_none:
        spec = parse_spec(signature.returned, described)
        if not _copied(spec, described):
            return None
        assert spec is not None
        specs["r"] = spec
    return _Crossing(specs, list(signature.classes), fields)


def crosses_in_c(signature: NativeSignature) -> bool:
    """Whether the generated wrapper copies this function's containers itself."""
    return signature.crosses_collections and _crossing(signature) is not None


def wrapped_in_c(signature: NativeSignature) -> bool:
    """Whether a generated wrapper serves this function: one whose containers,
    if any, `crossing.c` copies. A module global the function reads is an
    argument after Python's, which the binder reads for it (`bind_globals`)."""
    return not signature.crosses_collections or _crossing(signature) is not None


def _crossing_structs(index: int, crossing: _Crossing) -> str:
    """Each crossed type as static `ppy_xs` structs, inner ones first, and the
    classes as a `px_classes` table whose Python classes the first call finds."""
    lines: list[str] = []
    position = {c.qualname: number for number, c in enumerate(crossing.classes)}

    def emit(spec: Spec, name: str) -> str:
        key = emit(spec.key, f"{name}k") if spec.key is not None else ""
        value = emit(spec.value, f"{name}v") if spec.value is not None else ""
        parts = "".join(_PARTS[p] for p in spec.parts)
        cls = position.get(spec.record, -1) if spec.kind in {"object", "record"} else -1
        lines.append(
            f"static const ppy_xs {name} = {{{_CROSSING_KINDS[spec.kind]}, {len(spec.parts)}, "
            f'"{parts}", {"&" + key if key else "NULL"}, {"&" + value if value else "NULL"}, '
            f"{cls}, {int(spec.nullable)}}};"
        )
        return name

    for tag, spec in crossing.specs.items():
        emit(spec, f"ppy_xs_{index}_{tag}")
    if not crossing.classes:
        return "\n".join(lines)
    entries = []
    for number, c in enumerate(crossing.classes):
        if c.kind == "record":
            fields = [f'{{"{name}", {offset}, NULL}}' for name, offset, _kind in c.fields]
        else:
            fields = [
                f'{{"{name}", {offset}, &{emit(spec, f"ppy_xs_{index}_c{number}_{field}")}}}'
                for field, (name, offset, spec) in enumerate(crossing.fields[c.qualname])
            ]
        lines.append(
            f"static const px_field ppy_fields_{index}_{number}[] = "
            f"{{{', '.join(fields) or '{NULL, 0, NULL}'}}};"
        )
        bases = [str(position[b]) for b in c.bases if b in position]
        lines.append(
            f"static const int ppy_bases_{index}_{number}[] = {{{', '.join(bases) or '-1'}}};"
        )
        entries.append(
            f'    {{"{c.qualname}", {int(c.kind == "record")}, {c.tag}LL, {c.words}, {c.floats}LL, '
            f"{c.handles}LL, {len(c.fields)}, ppy_fields_{index}_{number}, {len(bases)}, "
            f"ppy_bases_{index}_{number}, NULL, NULL, {int(c.resident)}}},"
        )
    lines.append(f"static px_class ppy_classlist_{index}[] = {{\n" + "\n".join(entries) + "\n};")
    lines.append(
        f"static px_classes ppy_classes_{index} = "
        f"{{{len(crossing.classes)}, ppy_classlist_{index}, NULL, 0}};"
    )
    return "\n".join(lines)


def _c_atom(atom: str) -> str:
    return C_TYPES[atom.removesuffix("*")] + ("*" if atom.endswith("*") else "")


def _function(index: int, signature: NativeSignature, *, managed: bool = True) -> str:
    """One function's wrapper. `managed` is a boundary the runtime binds, which
    holds output (`wrapper_effects.c`); an extension's links its own code."""
    atoms = [_c_atom(atom) for atom in signature.params]
    outs = [
        "char **, long long *" if atom == "text" else f"{_c_atom(atom)} *"
        for atom in signature.returns
    ]
    pointer = f"ppy_fn_{index}"
    count = len(signature.parameters)
    copied = _crossing(signature) if signature.crosses_collections else None
    crossing = copied is not None
    specs = copied.specs if copied is not None else None
    classes = f"&ppy_classes_{index}" if copied is not None and copied.classes else "NULL"

    object_params = [p for p in signature.parameters if p.is_object]
    type_slots = "\n".join(
        f"static PyTypeObject *ppy_type_{index}_{position} = NULL;"
        for position, _p in enumerate(object_params)
    )
    # Field names are interned once, so a call is a dict lookup rather than a
    # fresh string on every attribute read.
    name_slots = "\n".join(
        f"static PyObject *ppy_name_{index}_{position}_{offset} = NULL;"
        for position, parameter in enumerate(object_params)
        for offset, _field in enumerate(parameter.fields)
    )

    declarations, body, cleanup, arguments = _parse_arguments(index, signature)
    out_declarations = "\n".join(
        f"    char *ppy_out{position} = NULL;\n    long long ppy_out{position}_len = 0;"
        if atom == "text"
        else f"    {_c_atom(atom)} ppy_out{position};"
        for position, atom in enumerate(signature.returns)
    )
    out_arguments = ", ".join(
        f"&ppy_out{position}, &ppy_out{position}_len" if atom == "text" else f"&ppy_out{position}"
        for position, atom in enumerate(signature.returns)
    )
    call_arguments = ", ".join([*arguments, out_arguments]) if arguments else out_arguments

    # Arguments are already machine values here and the result is built after
    # the call returns, so a body that cannot reach the interpreter may run
    # without the GIL (spec 16.6). A borrowed buffer stays pinned across it.
    release = "    Py_BEGIN_ALLOW_THREADS" if signature.releases_gil else ""
    acquire = "    Py_END_ALLOW_THREADS" if signature.releases_gil else ""
    if signature.releases_gil and crossing:
        # Resident objects (`crossing.c`) are only touched with the GIL held.
        release = "    PyThreadState *ppy_saved = ppy_x.resident ? NULL : PyEval_SaveThread();"
        acquire = "    if (ppy_saved != NULL) PyEval_RestoreThread(ppy_saved);"

    builder = _result_builder(index, signature)
    # A container crossing: the arguments copied in as the guards run, every
    # container that came in copied back after a call that writes, and the
    # handles the call held let go of on every way out, before a sweep.
    end = "    px_end(&ppy_x);\n" if crossing else ""
    # The arena of a call that writes through no parameter (`crossing.c`):
    # given back once nothing can read it any more, the last thing before
    # each way out; an answered call keeps what escaped it.
    close = "    px_close(&ppy_x);\n" if crossing else ""
    keep = "    px_keep(&ppy_x);\n" if crossing else ""
    readonly = int(copied is not None and _reads_only(signature, copied))
    sync = ""
    objects = _object_positions(signature, copied) if copied is not None else []
    resident = bool(objects) and classes != "NULL"
    if resident:
        # The fields native code wrote in resident objects, set on them.
        sync = (
            "    if (ppy_x.resident && px_drain(&ppy_x) < 0) {\n        px_end(&ppy_x);\n"
            "        px_close(&ppy_x);\n        return NULL;\n    }\n"
        )
    if crossing and any(p.is_handle and p.written for p in signature.parameters):
        sync += (
            "    if (px_sync(&ppy_x) < 0) {\n        px_end(&ppy_x);\n        px_close(&ppy_x);\n"
            "        return NULL;\n    }\n"
        )
    if crossing:
        # Every variable is declared before the first jump to the cleanup.
        declarations = "    ppy_cross ppy_x;\n" + declarations
        body = (
            f"    px_begin(&ppy_x, {classes}, {readonly});\n"
            "    if (!ppy_rt_ready) goto ppy_fallback;\n"
            + (f"    if (!px_resolve({classes})) goto ppy_fallback;\n" if classes != "NULL" else "")
            + (
                f"    px_resident(&ppy_x, args, ppy_objects_{index}, {len(objects)});\n"
                if resident
                else ""
            )
            + body
        )
    boxed = _box(signature).replace("ppy_build_result(", f"ppy_build_result_{index}(")
    if signature.returns_none:
        boxed = "Py_NewRef(Py_None)"
    elif crossing and specs is not None and "r" in specs:
        boxed = f"px_result(&ppy_x, (int8_t *)ppy_out0, &ppy_xs_{index}_r)"
    structs = _crossing_structs(index, copied) if copied is not None else ""
    if resident:
        structs += f"\nstatic const int ppy_objects_{index}[] = {{{', '.join(map(str, objects))}}};"
    resolver = ""
    if classes != "NULL":
        # The classes' Python classes are found at the first call, by this.
        resolver = (
            "    if (resolve != NULL && resolve != Py_None) {\n"
            "        Py_INCREF(resolve);\n"
            f"        Py_XDECREF(ppy_classes_{index}.resolve);\n"
            f"        ppy_classes_{index}.resolve = resolve;\n"
            "    }\n"
        )
    held = managed and signature.effects
    qualname = signature.qualname
    enter = leave = ""
    sanitized = f'{end}{close}        return ppy_sanitizer_failed(status, "{qualname}");\n'
    failed = (
        f"{end}        if (status == -1) {{\n            ppy_raised((void *)chosen);\n        }}\n"
        f"{close}"
        f"        return ppy_handoff_as(ppy_fallback_{index}, ppy_given, ppy_count, kwnames);\n"
    )
    made = "    px_resident_result(&ppy_x, ppy_result);\n" if resident else ""
    answered = (
        f"{sync}    PyObject *ppy_result = {boxed};\n{made}{end}{keep}    return ppy_result;\n"
    )
    if held:
        # Output held while the call runs: written out once it answers,
        # dropped where it falls back, and a call that raised after a
        # barrier raises at the boundary (`wrapper_effects.c`).
        body = "    if (!ppy_io_ready) goto ppy_fallback;\n" + body
        enter = "    int64_t ppy_outer = ppy_io.enter();\n"
        leave = "    int64_t ppy_crossed = ppy_io.leave(ppy_outer);\n"
        sanitized = (
            f"{end}{close}        ppy_io.discard();\n        ppy_io_settle();\n"
            f'        return ppy_sanitizer_failed(status, "{qualname}");\n'
        )
        crossed = f'ppy_io_crossed(status, "{qualname}")'
        if crossing:
            crossed = f'ppy_closed(ppy_io_crossed(status, "{qualname}"), &ppy_x)'
        failed = (
            f"{end}        if (ppy_crossed) {{\n"
            f"            return {crossed};\n        }}\n"
            "        ppy_io.discard();\n"
            "        if (status == -1) {\n            ppy_raised((void *)chosen);\n        }\n"
            f"{close}"
            "        ppy_io_settle();\n"
            f"        return ppy_handoff_as(ppy_fallback_{index}, ppy_given, ppy_count, kwnames);\n"
        )
        synced = sync.replace("return NULL;", "return ppy_io_commit_result(NULL);")
        answered = (
            f"{synced}    PyObject *ppy_result = {boxed};\n{made}"
            f"{end}    ppy_result = ppy_io_commit_result(ppy_result);\n"
            f"{keep}    return ppy_result;\n"
        )
    draws = managed and signature.draws
    if draws:
        # `random`'s state as the call found it (`_DRAWS`).
        declarations = "    unsigned char ppy_drawn[PPY_DRAW_BYTES];\n" + declarations
        # Without the state's address, the Python-side binding saves it.
        body = (
            "    if (ppy_draw_state != NULL) memcpy(ppy_drawn, ppy_draw_state, PPY_DRAW_BYTES);\n"
            + body
        )
        # Put back only where Python runs the call again: not after a barrier.
        failed = failed.replace(
            "        return ppy_handoff_as(",
            "        ppy_draw_restore(ppy_drawn);\n        return ppy_handoff_as(",
        )
        answered = "    ppy_draw_settle();\n" + answered
    return f"""
/* {signature.qualname}: {signature} */
{structs}
typedef int (*{pointer})({", ".join([*atoms, *outs])});
static {pointer} ppy_target_{index} = NULL;
static ppy_spec ppy_specs_{index}[PPY_MAX_SPECS];
static int ppy_spec_count_{index} = 0;
static PyObject *ppy_types_{index} = NULL;
static PyObject *ppy_fallback_{index} = NULL;
static PyObject *ppy_keyed_{index} = NULL;
static ppy_binder ppy_binder_{index} = {{NULL, NULL, 0, 0}};
{type_slots}
{name_slots}
{builder}

static PyObject *ppy_call_{index}(PyObject *, PyObject *const *, Py_ssize_t, PyObject *);

static PyObject *ppy_bind_{index}(PyObject *self, PyObject *args) {{
    unsigned long long address;
    PyObject *types;
    PyObject *fallback = NULL;
    PyObject *resolve = NULL;
    if (!PyArg_ParseTuple(args, "KO|OO", &address, &types, &fallback, &resolve)) {{
        return NULL;
    }}
    if (fallback == Py_None) {{
        fallback = NULL;
    }}
{resolver}
    Py_XINCREF(types);
    Py_XDECREF(ppy_types_{index});
    ppy_types_{index} = types;
    Py_XINCREF(fallback);
    Py_XDECREF(ppy_fallback_{index});
    ppy_fallback_{index} = fallback;
    ppy_target_{index} = ({pointer})(uintptr_t)address;
    ppy_binder_set(&ppy_binder_{index}, fallback, {count});
{_type_assignments(index, object_params)}    ppy_spec_count_{index} = 0;
    if (fallback != NULL) {{
        return ppy_named((PyCFunction)(void *)ppy_call_{index}, fallback);
    }}
    Py_RETURN_NONE;
}}

static PyObject *ppy_keyed_set_{index}(PyObject *self, PyObject *args) {{
    PyObject *keyed = NULL;
    if (!PyArg_ParseTuple(args, "O", &keyed)) {{
        return NULL;
    }}
    Py_INCREF(keyed);
    Py_XDECREF(ppy_keyed_{index});
    ppy_keyed_{index} = keyed == Py_None ? NULL : keyed;
    if (keyed == Py_None) {{
        Py_DECREF(keyed);
    }}
    Py_RETURN_NONE;
}}

static PyObject *ppy_specialize_{index}(PyObject *self, PyObject *args) {{
    int added = ppy_add_spec(ppy_specs_{index}, &ppy_spec_count_{index}, args);
    if (added < 0) {{
        return NULL;
    }}
    return PyBool_FromLong(added);
}}

static PyObject *ppy_call_{index}(
    PyObject *self, PyObject *const *ppy_given, Py_ssize_t ppy_count, PyObject *kwnames
) {{
    /* The arguments in the entry's order: as given, or bound from keywords
       and defaults. A refusal hands Python the call as it was spelled. */
    PyObject *const *args = ppy_given;
    Py_ssize_t nargs = ppy_count;
    PyObject *ppy_bound[{max(count, 1)}];
    if ((kwnames != NULL && PyTuple_GET_SIZE(kwnames) > 0)
        || (ppy_target_{index} != NULL && nargs != {count})) {{
        if (ppy_target_{index} != NULL && ppy_binder_{index}.function != NULL) {{
            if (ppy_bind_call(
                    &ppy_binder_{index}, ppy_given, ppy_count, kwnames, ppy_bound, {count})) {{
                args = ppy_bound;
                nargs = {count};
                goto ppy_bound_call;
            }}
            /* What does not bind here does not bind: Python raises its TypeError. */
            return PyObject_Vectorcall(ppy_fallback_{index}, ppy_given, ppy_count, kwnames);
        }}
        /* Python binds keywords and defaults (`binding.keyed`), then calls
           this entry in order; without a binder the Python function runs. */
        if (ppy_keyed_{index} != NULL) {{
            return PyObject_Vectorcall(ppy_keyed_{index}, args, nargs, kwnames);
        }}
        if (ppy_fallback_{index} == NULL) {{
            Py_RETURN_NOTIMPLEMENTED;
        }}
        return PyObject_Vectorcall(ppy_fallback_{index}, args, nargs, kwnames);
    }}
    if (ppy_target_{index} == NULL) {{
        return ppy_handoff(ppy_fallback_{index}, args, nargs);
    }}
ppy_bound_call:;
    {pointer} chosen = ppy_target_{index};
    for (int slot = 0; slot < ppy_spec_count_{index}; slot++) {{
        if (ppy_spec_matches(&ppy_specs_{index}[slot], args, nargs)) {{
            chosen = ({pointer})ppy_specs_{index}[slot].target;
            break;
        }}
    }}
{declarations}
{body}
{out_declarations}
    int status = 0;
{enter}{release}
    status = chosen({call_arguments});
{acquire}
{leave}{cleanup}
    if (status >= 2) {{
{sanitized}    }}
    if (status != 0) {{
{failed}    }}
{answered}
ppy_fallback:
{cleanup}
{end}{close}    return ppy_handoff_as(ppy_fallback_{index}, ppy_given, ppy_count, kwnames);
}}
"""


def _object_positions(signature: NativeSignature, crossing: _Crossing) -> list[int]:
    """The arguments that are objects of the project's classes, or lists of
    them, which a call keeps resident (`crossing.c`) where they crossed
    before; a list's position is spelled negative, less one."""
    found = []
    for position, parameter in enumerate(signature.parameters):
        spec = crossing.specs.get(str(position)) if parameter.is_handle else None
        if spec is None:
            continue
        if spec.kind == "object":
            found.append(position)
        elif spec.kind == "list" and spec.value is not None and spec.value.kind == "object":
            found.append(-position - 1)
    return found


def _reads_only(signature: NativeSignature, crossing: _Crossing) -> bool:
    """Whether a call's containers may be laid out in its arena (`crossing.c`):
    it writes through no parameter, and none holds an object, whose fields
    `getattr` reads and which may be in a cycle with what holds it."""

    def plain(spec: Spec | None) -> bool:
        if spec is None:
            return True
        if spec.kind in {"object", "record"}:
            return False
        return plain(spec.key) and plain(spec.value)

    if any(p.is_handle and p.written for p in signature.parameters):
        return False
    return all(plain(spec) for tag, spec in crossing.specs.items() if tag != "r")


def _type_assignments(index: int, object_params: list[NativeParam]) -> str:
    lines = []
    for position, parameter in enumerate(object_params):
        lines.append(
            f"    ppy_type_{index}_{position} = (PyTypeObject *)PyTuple_GetItem(types, {position});"
        )
        for offset, (attr, _scalar) in enumerate(parameter.fields):
            slot = f"ppy_name_{index}_{position}_{offset}"
            lines.append(f'    if ({slot} == NULL) {slot} = PyUnicode_InternFromString("{attr}");')
            lines.append(f"    if ({slot} == NULL) return NULL;")
    return "\n".join(lines) + ("\n" if lines else "")


def _parse_arguments(index: int, signature: NativeSignature) -> tuple[str, str, str, list[str]]:
    """Emit the declarations, the parsing, the cleanup, and the call arguments.

    Every variable is declared and initialized up front, because a guard that
    fails jumps to the cleanup: a declaration skipped by that jump would leave
    the cleanup reading an indeterminate value.
    """
    declarations: list[str] = []
    lines: list[str] = []
    cleanup: list[str] = []
    arguments: list[str] = []
    object_position = 0

    for position, parameter in enumerate(signature.parameters):
        source = f"args[{position}]"
        if parameter.is_handle:
            # A container copied into native memory (`crossing.c`); one that
            # does not match its type runs the Python body.
            handle = f"h{position}"
            declarations.append(f"    int8_t *{handle} = NULL;")
            # Only what a written parameter brings in is copied back.
            lines.append(f"    ppy_x.writing = {int(parameter.written)};")
            lines.append(
                f"    if (px_argument(&ppy_x, {source}, &ppy_xs_{index}_{position}, &{handle})"
                " != 0) PPY_GUARD_FAIL();"
            )
            arguments.append(f"(char *){handle}")
            continue
        if parameter.is_object:
            slot = f"ppy_type_{index}_{object_position}"
            object_position += 1
            lines.append(
                f"    if ({slot} == NULL || Py_TYPE({source}) != {slot}) PPY_GUARD_FAIL();"
            )
            for offset, (attr, scalar) in enumerate(parameter.fields):
                name = f"a{position}_{attr}"
                interned = f"ppy_name_{index}_{object_position - 1}_{offset}"
                declarations.append(f"    {C_TYPES[_abi(scalar)]} {name} = 0;")
                lines.append("    {")
                lines.append(f"        PyObject *member = PyObject_GetAttr({source}, {interned});")
                lines.append("        if (member == NULL) PPY_GUARD_FAIL();")
                lines.extend(
                    _scalar_lines(
                        scalar, "member", name, "        ", release=True, exact=parameter.exact
                    )
                )
                lines.append("        Py_DECREF(member);")
                lines.append("    }")
                arguments.append(name)
            continue

        if parameter.is_tuple:
            lines.append(
                f"    if (!PyTuple_CheckExact({source}) || "
                f"PyTuple_GET_SIZE({source}) != {len(parameter.elements)}) PPY_GUARD_FAIL();"
            )
            for offset, scalar in enumerate(parameter.elements):
                name = f"a{position}_{offset}"
                declarations.append(f"    {C_TYPES[_abi(scalar)]} {name} = 0;")
                lines.extend(
                    _scalar_lines(
                        scalar,
                        f"PyTuple_GET_ITEM({source}, {offset})",
                        name,
                        "    ",
                        exact=parameter.exact,
                    )
                )
                arguments.append(name)
            continue

        if parameter.is_text:
            # The bytes are the string's own UTF-8, borrowed for the call; a
            # string with a lone surrogate has none, and stays in Python.
            data = f"text{position}"
            size = f"text{position}_len"
            declarations.append(f"    const char *{data} = NULL;")
            declarations.append(f"    Py_ssize_t {size} = 0;")
            lines.append(f"    if (!PyUnicode_CheckExact({source})) PPY_GUARD_FAIL();")
            lines.append(f"    {data} = PyUnicode_AsUTF8AndSize({source}, &{size});")
            lines.append(f"    if ({data} == NULL) PPY_GUARD_FAIL();")
            arguments.append(f"(char *){data}")
            arguments.append(f"(long long){size}")
            continue

        if parameter.is_borrowed:
            view = f"view{position}"
            declarations.append(f"    Py_buffer {view};")
            declarations.append(f"    int {view}_held = 0;")
            lines.append(
                f"    if (PyObject_GetBuffer({source}, &{view}, "
                f"PyBUF_WRITABLE | PyBUF_C_CONTIGUOUS | PyBUF_FORMAT) != 0) PPY_GUARD_FAIL();"
            )
            lines.append(f"    {view}_held = 1;")
            lines.append(
                f"    if ({view}.ndim != 1 || {view}.itemsize != {_itemsize(parameter.element)}"
                f" || {view}.format == NULL || !({_format_test(parameter.element, view)}))"
                f" PPY_GUARD_FAIL();"
            )
            cleanup.append(f"    if ({view}_held) PyBuffer_Release(&{view});")
            arguments.append(f"({C_TYPES[_abi(parameter.element)]} *){view}.buf")
            arguments.append(f"(long long){view}.shape[0]")
            continue

        if parameter.is_buffer:
            data = f"data{position}"
            count = f"count{position}"
            element = C_TYPES[_abi(parameter.element)]
            declarations.append(f"    {element} *{data} = NULL;")
            declarations.append(f"    Py_ssize_t {count} = 0;")
            if parameter.kind == "sequence":
                # `PySequence_Fast` returns the object itself for a list or a
                # tuple and builds a list otherwise, so one path serves every
                # sequence the caller may pass.
                fast = f"fast{position}"
                declarations.append(f"    PyObject *{fast} = NULL;")
                lines.append(f'    {fast} = PySequence_Fast({source}, "expected a sequence");')
                lines.append(f"    if ({fast} == NULL) {{ PyErr_Clear(); PPY_GUARD_FAIL(); }}")
                lines.append(f"    {count} = PySequence_Fast_GET_SIZE({fast});")
                cleanup.append(f"    Py_XDECREF({fast});")
                holder, size, item = fast, count, f"PySequence_Fast_GET_ITEM({fast}, i)"
            else:
                lines.append(f"    if (!PyList_CheckExact({source})) PPY_GUARD_FAIL();")
                lines.append(f"    {count} = PyList_GET_SIZE({source});")
                holder, size, item = source, count, f"PyList_GET_ITEM({source}, i)"
            assert holder is not None and size is not None
            lines.append(
                f"    {data} = ({element} *)PyMem_Malloc((size_t)({count} ? {count} : 1)"
                f" * sizeof({element}));"
            )
            lines.append(f"    if ({data} == NULL) PPY_GUARD_FAIL();")
            lines.append(f"    for (Py_ssize_t i = 0; i < {count}; i++) {{")
            lines.append(f"        PyObject *item = {item};")
            lines.extend(
                _scalar_lines(
                    parameter.element,
                    "item",
                    f"{data}[i]",
                    "        ",
                    declare=False,
                    exact=parameter.exact,
                )
            )
            lines.append("    }")
            cleanup.append(f"    PyMem_Free({data});")
            arguments.append(data)
            arguments.append(f"(long long){count}")
            continue

        name = f"a{position}"
        declarations.append(f"    {C_TYPES[_abi(parameter.kind)]} {name} = 0;")
        lines.extend(_scalar_lines(parameter.kind, source, name, "    ", exact=parameter.exact))
        arguments.append(name)

    return "\n".join(declarations), "\n".join(lines), "\n".join(cleanup), arguments


#: The largest int a double holds exactly, and every int below it: 2**53.
_EXACT = "9007199254740992LL"


def _scalar_lines(
    scalar: str,
    source: str,
    target: str,
    indent: str,
    *,
    declare: bool = True,
    release: bool = False,
    exact: bool = False,
) -> list[str]:
    """Parse one Python object into a machine scalar, or fail the guard.

    A `float` takes an `int` a double holds exactly, unless it is `exact`:
    then an `int` stays in Python, where it stays an `int`.
    """
    undo = f"{indent}    Py_DECREF({source});\n" if release else ""
    if scalar == "float" and exact:
        return [
            f"{indent}if (PyFloat_CheckExact({source})) {{",
            f"{indent}    {target} = PyFloat_AS_DOUBLE({source});",
            f"{indent}}} else {{",
            f"{undo}{indent}    PPY_GUARD_FAIL();",
            f"{indent}}}",
        ]
    if scalar == "float":
        return [
            f"{indent}if (PyFloat_CheckExact({source})) {{",
            f"{indent}    {target} = PyFloat_AS_DOUBLE({source});",
            f"{indent}}} else if (PyLong_CheckExact({source})) {{",
            f"{indent}    long long whole = PyLong_AsLongLong({source});",
            (
                f"{indent}    if ((whole == -1 && PyErr_Occurred())"
                f" || whole > {_EXACT} || whole < -{_EXACT}) {{"
            ),
            f"{undo}{indent}        PPY_GUARD_FAIL();",
            f"{indent}    }}",
            f"{indent}    {target} = (double)whole;",
            f"{indent}}} else {{",
            f"{undo}{indent}    PPY_GUARD_FAIL();",
            f"{indent}}}",
        ]
    if scalar == "bool":
        return [
            f"{indent}if (!PyBool_Check({source})) {{",
            f"{undo}{indent}    PPY_GUARD_FAIL();",
            f"{indent}}}",
            f"{indent}{target} = ({source} == Py_True) ? 1 : 0;",
        ]
    return [
        f"{indent}if (!PyLong_CheckExact({source})) {{",
        f"{undo}{indent}    PPY_GUARD_FAIL();",
        f"{indent}}}",
        f"{indent}{target} = PyLong_AsLongLong({source});",
        f"{indent}if ({target} == -1 && PyErr_Occurred()) {{",
        f"{undo}{indent}    PPY_GUARD_FAIL();",
        f"{indent}}}",
    ]


def _box(signature: NativeSignature) -> str:
    """Build the Python object the wrapper returns."""
    if len(signature.returns) == 1:
        return _box_one(signature.returns[0], "ppy_out0")
    return (
        "ppy_build_result("
        + ", ".join(f"ppy_out{position}" for position in range(len(signature.returns)))
        + ")"
    )


def _result_builder(index: int, signature: NativeSignature) -> str:
    """A tuple result is built element by element, so no format string is
    needed and a failed allocation cannot leak the elements already boxed."""
    if len(signature.returns) == 1:
        return ""
    parameters = ", ".join(
        f"{C_TYPES[atom]} v{position}" for position, atom in enumerate(signature.returns)
    )
    sets = "\n".join(
        f"    PyObject *b{position} = {_box_one(atom, f'v{position}')};\n"
        f"    if (b{position} == NULL) {{ Py_DECREF(result); return NULL; }}\n"
        f"    PyTuple_SET_ITEM(result, {position}, b{position});"
        for position, atom in enumerate(signature.returns)
    )
    return f"""
static PyObject *ppy_build_result_{index}({parameters}) {{
    PyObject *result = PyTuple_New({len(signature.returns)});
    if (result == NULL) return NULL;
{sets}
    return result;
}}
"""


def _box_one(atom: str, name: str) -> str:
    if atom == "text":
        return f"ppy_text_result({name}, {name}_len)"
    if atom == "double":
        return f"PyFloat_FromDouble({name})"
    if atom == "i8":
        return f"PyBool_FromLong({name})"
    return f"PyLong_FromLongLong({name})"


def _abi(scalar: str) -> str:
    return {"int": "i64", "float": "double", "bool": "i8", "i8": "i8", "u8": "i8"}[scalar]


def _itemsize(element: str) -> int:
    """A byte element is one byte wide; everything else is a machine word."""
    return 1 if element in {"i8", "u8"} else 8


#: Buffer-protocol format codes each element accepts. Signedness is part of
#: the element: accepting `B` for an `i8` would read 255 as -1, which is a
#: different answer rather than a slower one.
_FORMATS = {
    "float": ("d",),
    "int": ("q", "l"),
    "i8": ("b",),
    "u8": ("B",),
}


def _format_test(element: str, view: str) -> str:
    codes = _FORMATS.get(element, ("q", "l"))
    return " || ".join(f"{view}.format[0] == '{code}'" for code in codes)
