"""The typed canonical IR: what sits between analysis and every backend.

`model` is the data structure, `types` the types, `dialect` the extension
point, `dialects.core` what every backend lowers, `verify` the rules,
`printer`/`parser`/`codec` the text form. See `docs/ir.md`.
"""

from __future__ import annotations

from .codec import IR_SCHEMA_VERSION, CodecError, decode, encode, read, write
from .dialect import Dialect, DialectRegistry, OpSpec, registry
from .model import (
    Attribute,
    Block,
    BlockArgument,
    Builder,
    Global,
    IRFunction,
    IRModule,
    Operation,
    OpResult,
    Region,
    SourceLocation,
    Successor,
    Symbol,
    SymbolRef,
    Value,
)
from .parser import ParseError, parse_module
from .printer import print_function, print_module
from .types import (
    BOOL,
    F16,
    F32,
    F64,
    I8,
    I16,
    I32,
    I64,
    INDEX,
    U8,
    U16,
    U32,
    U64,
    VOID,
    BoolType,
    BufferType,
    DialectType,
    FloatType,
    FutureType,
    IndexType,
    IntType,
    IRType,
    PtrType,
    StructType,
    TupleType,
    VectorType,
    VoidType,
    parse_type,
)
from .verify import VerificationError, VerifyError, verify, verify_or_raise

__all__ = [
    "BOOL",
    "F16",
    "F32",
    "F64",
    "I8",
    "I16",
    "I32",
    "I64",
    "INDEX",
    "IR_SCHEMA_VERSION",
    "U8",
    "U16",
    "U32",
    "U64",
    "VOID",
    "Attribute",
    "Block",
    "BlockArgument",
    "BoolType",
    "BufferType",
    "Builder",
    "CodecError",
    "Dialect",
    "DialectRegistry",
    "DialectType",
    "FloatType",
    "FutureType",
    "Global",
    "IRFunction",
    "IRModule",
    "IRType",
    "IndexType",
    "IntType",
    "OpResult",
    "OpSpec",
    "Operation",
    "ParseError",
    "PtrType",
    "Region",
    "SourceLocation",
    "StructType",
    "Successor",
    "Symbol",
    "SymbolRef",
    "TupleType",
    "Value",
    "VectorType",
    "VerificationError",
    "VerifyError",
    "VoidType",
    "decode",
    "encode",
    "parse_module",
    "parse_type",
    "print_function",
    "print_module",
    "read",
    "registry",
    "verify",
    "verify_or_raise",
    "write",
]
